### ISSUE TITLE
extensions option ignored

### ISSUE THREAD

**Issue by paulrobertlloyd** [berrberr/guard-jekyll-plus#3]
Hello,

Regardless of how I configure extension options (either declared explicitly or not at all), a Jekyll build is initiated. This is the line in my Guardfile:

``` ruby
guard 'jekyll-plus', :config => ['config/jekyll.yml', 'config/jekyll/development.yml'] do
  watch(%r{^source/.+})
end
```

This is a problem particularly when I make a change to any .scss file that lives within Jekyll’s source directory. To stop this behaviour, I’ve had to declare file extensions in watch(), like so:

``` ruby
guard 'jekyll-plus', :config => ['config/jekyll.yml', 'config/jekyll/development.yml'] do
  watch(%r{^source/.+\.(txt|markdown|html|yml|xml)})
end
```

This would appear broken. Am I doing something wrong? For context, here is my entire Guardfile:

``` ruby
# Jekyll https://github.com/berrberr/guard-jekyll-plus
guard 'jekyll-plus', :config => ['config/jekyll.yml', 'config/jekyll/development.yml'] do
  watch(%r{^source/.+\.(txt|markdown|html|yml|xml)})
end

# Sass https://github.com/hawx/guard-sass
guard 'sass', :output => 'public/assets/', :syntax => :scss, :shallow => true do
  watch(%r{^source/.+\.scss})
end

# LiveReload https://github.com/guard/guard-livereload
guard 'livereload', override_url: true do
  watch(%r{^public/.+})
end
```

**Comment by berrberr** [comment]
Hey, by default files with the following extensions will be passed to the jekyll build:

``` ruby
default_extensions = ['md','mkd','mkdn','markdown','textile','html','haml','slim','xml','yml','coffee','sass','scss']
```

Files that do not match those extensions are passed to the static copy function when changed, and they will be copied into the site output dir.

If you want to ignore certain files then you can add them to the `exclude` array in your Jekyll config file.  Any file matching a pattern in the `exclude` arr will be skipped by the copy and build methods.

So one option for you is to keep your Guard file like:

``` ruby
guard 'jekyll-plus', :config => ['config/jekyll.yml', 'config/jekyll/development.yml'] do
  watch(%r{^source/.+})
end
```

and then add

``` ruby
exclude: ['**.scss']
```

to your config file. Doing that will ensure that any changes to `.scss` files are ignored by guard (well they are still detected but no action is performed on them) _and_ won't be copied to the site build dir.

Hopefully I didn't misunderstand your question. Also, be sure to update this gem from repo as I just fixed a bug where the build process didn't detect excluded files. Let me know if this helps!

**Comment by paulrobertlloyd** [comment]
Thanks for the reply. However, I'm this is still not working as expected. Adding `exclude: ['**.scss']` to my Jekyll has no effect. Besides, all my .scss files are within a folder called `_stylesheets`, so are excluded and not built anyway, given the underscore. I have updated the gem before trying these suggestions. Basically, any file that is changed within the source folder, kicks off a rebuild :-(

(For reference, my site source code can be found here: https://github.com/paulrobertlloyd/paulrobertlloyd.com/)

**Comment by berrberr** [comment]
Strange... I just tried the following in your project and it worked:

In `config/jekyll.yml` I added

``` ruby
exclude: ['**.scss']
```

then I ran `guard` and modified `source/_stylesheets/_vars.scss`. Output:

```
22:25:07 - INFO - Jekyll skip build on file: 'source/_stylesheets/_vars.scss'
22:25:07 - INFO - Sass [0.14s] source/_stylesheets/global.scss -> global.css
22:25:07 - INFO - Reloading browser: public/assets/global.css
```

So my changes to the sass file were skipped by the Jekyll build, passed into sass and then triggered livereload. Is this not the expected/intended behavior?

**Comment by paulrobertlloyd** [comment]
Tried your suggestion again, and you were right, it does work! (Think I may have originally written the config directive as an array within an array). I now also understand why I need to add this exclude value, too. Closing this issue.

P.S. Thanks for updating (and basically maintaining) this guard plugin; it's been enormously helpful. Do you think your changes will ever make it into the main project?

**Comment by berrberr** [comment]
Great, glad it's working! :smile: 

Yes, at some point when I get some free time (soon I think) I'd like to finish adding a few more of the missing features and merge everything into the main gem (since right now it is somewhat broken!)
